# Generated by Django 5.1.3 on 2024-11-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User_Register_Table',
        ),
    ]
