# Generated by Django 5.1.3 on 2024-11-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_rename_register_user_register_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Register_Table',
            new_name='UserRegisterTable',
        ),
    ]
