# Generated by Django 5.1.3 on 2024-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_rename_user_register_table_userregistertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistertable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
